version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5431:5432'
    networks:
      - taxicube
    volumes:
            - ./conf/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taxicube"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    container_name: vismetabase
    depends_on:
      - postgres
    hostname: metabase
    build: metabase/ # Dockerfile we created for metabase
    volumes:
      - ./conf/metabase:/conf
    ports:
      - 3030:3030
    networks:
      - taxicube

  cube:
    image: cubejs/cube
    container_name: cube
    hostname: cube
    volumes:
      - ./conf/cube:/cube/conf
    ports:
      - 3000:3000
      - 4000:4000
      - 3245:3245
    networks:
      - taxicube
    depends_on:
      - postgres

networks:
  taxicube:
    driver: bridge
